server {
    listen 80;
    root /usr/share/nginx/html;
    client_max_body_size 25m;
    location /core/ {
        proxy_pass http://delta-core:8000/;
        proxy_read_timeout 180s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location /tasks-api/ { proxy_pass http://delta-tasks:8000/; }
    location / { try_files $uri $uri/ /index.html; }
}
