import {FormEvent,useEffect,useState} from 'react';
import {Folder,Plus,Play,ArrowLeft} from 'lucide-react';
import {Workspace,Device,Task,getWorkspaces,getDevices,getTasks,saveWorkspace,saveBinding,deleteWorkspace,launchWorkspace} from './api';

export function Workspaces(){
  const [rows,setRows]=useState<Workspace[]>([]);const [devices,setDevices]=useState<Device[]>([]);const [tasks,setTasks]=useState<Task[]>([]);
  const [selected,setSelected]=useState<string|null>(null);const [editor,setEditor]=useState(false);const [deviceId,setDeviceId]=useState('');
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [result,setResult]=useState('');
  const current=rows.find(w=>w.id===selected);
  const binding=current?.bindings?.find(b=>b.device_id===deviceId);
  async function refresh(){try{const [w,d,t]=await Promise.all([getWorkspaces(),getDevices(),getTasks()]);setRows(w);setDevices(d);setTasks(t);setError('');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer);},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const data=new FormData(event.currentTarget);try{await saveWorkspace({name:String(data.get('name')),description:String(data.get('description'))},current?.id);setEditor(false);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function bind(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!current)return;setBusy(true);const data=new FormData(event.currentTarget);try{await saveBinding(current.id,{device_id:deviceId,local_path:String(data.get('local_path')),apps:data.getAll('apps').map(String),urls:String(data.get('urls')).split('\n').map(s=>s.trim()).filter(Boolean)});await refresh();setResult('Привязка сохранена');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function launch(){if(!current)return;setBusy(true);setResult('');try{const result=await launchWorkspace(current.id,deviceId);setResult(result.message+'\n'+result.results.map(r=>`${r.success?'✓':'×'} ${r.message}`).join('\n'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <>{error&&<div className="error" role="alert">{error}</div>}<div className="toolbar">{selected?<button onClick={()=>{setSelected(null);setEditor(false);setResult('');}}><ArrowLeft size={15}/> Все пространства</button>:<span>{rows.length} workspaces</span>}<button className="primary" onClick={()=>{setSelected(null);setEditor(true);}}><Plus size={15}/> Новое пространство</button></div>
    {editor&&<article className="editor"><form key={current?.id||'new'} onSubmit={save}><label>Название пространства<input name="name" required defaultValue={current?.name}/></label><label>Описание пространства<textarea name="description" defaultValue={current?.description}/></label><div className="actions"><button className="primary" disabled={busy}>Сохранить пространство</button><button type="button" onClick={()=>setEditor(false)}>Отмена</button></div></form></article>}
    {current?<><article><div className="section-heading"><h2>{current.name}</h2><div className="actions"><button onClick={()=>setEditor(true)}>Редактировать</button><button onClick={async()=>{if(!confirm('Удалить пространство? Задачи сохранятся.'))return;try{await deleteWorkspace(current.id);setSelected(null);await refresh();}catch(e){setError((e as Error).message);}}}>Удалить</button></div></div><p>{current.description||'Описание не задано'}</p><label>Устройство<select aria-label="Устройство" value={deviceId} onChange={e=>{setDeviceId(e.target.value);setResult('');}}><option value="">Выберите устройство</option>{devices.map(d=><option key={d.id} value={d.id}>{d.display_name} · {d.status}</option>)}</select></label>
    {deviceId&&<form key={deviceId+JSON.stringify(binding)} onSubmit={bind}><label>Каталог проекта<input name="local_path" defaultValue={binding?.local_path} placeholder="Абсолютный путь на выбранном устройстве"/></label><div className="checks"><label><input type="checkbox" name="apps" value="vscode" defaultChecked={binding?.apps.includes('vscode')}/> Visual Studio Code</label><label><input type="checkbox" name="apps" value="browser" defaultChecked={binding?.apps.includes('browser')}/> Browser</label></div><label>Сайты — по одному адресу на строке<textarea name="urls" defaultValue={binding?.urls.join('\n')} placeholder="https://example.com"/></label><div className="actions"><button disabled={busy}>Сохранить привязку</button><button className="primary" type="button" disabled={busy||!binding||devices.find(d=>d.id===deviceId)?.status!=='online'} onClick={launch}><Play size={14}/> Launch Workspace</button></div></form>}{result&&<pre role="status">{result}</pre>}</article><h2>Задачи пространства</h2><article>{tasks.filter(t=>t.workspace_id===current.id).map(t=><p key={t.id}>{t.status==='done'?'✓':'○'} {t.title}</p>)}{!tasks.some(t=>t.workspace_id===current.id)&&<p>Связанных задач пока нет</p>}</article></>:<div className="grid">{rows.map(w=><button className="device-card" key={w.id} onClick={()=>{setSelected(w.id);setEditor(false);setDeviceId(w.bindings?.[0]?.device_id||'');setResult('');}}><Folder size={24}/><h2>{w.name}</h2><p>{w.description||'Workspace'}</p><small>{w.bindings?.length||0} devices · {w.bindings?.reduce((n,b)=>n+b.apps.length,0)||0} apps · {w.bindings?.reduce((n,b)=>n+b.urls.length,0)||0} URLs · {tasks.filter(t=>t.workspace_id===w.id&&t.status!=='done').length} open tasks</small></button>)}{!rows.length&&!editor&&<article className="empty">Создайте первое рабочее пространство</article>}</div>}
  </>;
}
